name: Publish Fixture Calendar

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '1 0 * * 1-2'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Create dist directory'
        run: mkdir -p dist

      - name: 'Scrape Website for Fixtures'
        run: node scripts/get-team-pages.js

      - name: 'Extract html fixtures to json'
        run: node scripts/html-to-json-fixtures.js

      - name: 'Extract html results to json'
        run: node scripts/html-to-json-results.js

      - name: 'Convert json Fixtures to ics'
        run: node scripts/json-to-ics.js

      - name: Create/Update 'latest' Release with Calendar
        uses: softprops/action-gh-release@v1
        with:
          name: 'Latest Fixtures Calendar'
          tag_name: 'latest'
          fail_on_unmatched_files: true
          body: 'This release contains the most up-to-date fixtures for each team. Subscribe to the .ics files below.'
          files: dist/*.ics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
